# Generated by Django 3.2.5 on 2021-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('photo', 'photo')], max_length=20, null=True),
        ),
    ]
